### ISSUE TITLE
Ensure csm-support is disabled

### ISSUE THREAD

**Issue by kolsa** [metal-stack/metal-hammer#18]
`metal-hammer` currently ensures UEFI mode via
```
if firmware != "efi" && !spec.DevMode {
    err = hammer.EnsureUEFI()
}
```
This additionally disables the csm-support, which is required.

We observed the case that there are a few machines booting in UEFI mode, but have the csm-support enabled. Thus the check above will skip `hammer.EnsureUEFI()` and therewith missing to disable csm-support.

Solution: `metal-hammer` needs to *always* read BIOS settings via sum tool and check not only for UEFI mode but also for disabled csm-support.

**Comment by kolsa** [comment]
#19 enables secure-boot for bigtwin, which in turn disables csm-support automatically

**Comment by majst01** [comment]
can we close this ?

**Comment by kolsa** [comment]
Already implemented
