### ISSUE TITLE
Hard-coded sizes for primary disk device

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-hammer#22]
This part here does only work for our specific sizes (not for anyone else) and we would need to-recompile a new metal-hammer version if something changes: https://github.com/metal-stack/metal-hammer/blob/v0.5.3/cmd/storage/disk.go#L150-L155

I think we should deal with this differently. One idea that comes to mind is storing the primary disk preference in the metal-api size as well and just use it from there. Otherwise, guess.

**Comment by majst01** [comment]
@kolsa and me already discussed this during the grpc-alloc phase. I already described this in the original proposal. We dropped the idea to add this special feature and decided to implement this in another round. I search for my proposal and will put it here and in metal-api for further reference

**Comment by majst01** [comment]
we should address this with [MEP-8](https://github.com/metal-stack/docs/pull/54)

**Comment by majst01** [comment]
#50 is merged, closing
