### ISSUE TITLE
Need for a technical bmc user for maintenance purposes inside a partition

### ISSUE THREAD

**Issue by muhittink** [metal-stack/metal-hammer#25]
There is a need for a technical user to achieve maintenance work inside a partition from the local network. 
The user and the strong password should be all the same among the bmcs in a partition.
For additional security reasons, it also makes sense to enable the "IP Access Control" from specific source IPs.

**Comment by kolsa** [comment]
I would reuse `metal` for this purpose and give him the preset password rather than a generated one

**Comment by majst01** [comment]
closed because #101 was merge
