### ISSUE TITLE
No matching versions for query "latest". Can't compile Go files with gollvm

### ISSUE THREAD

**Issue by advancedwebdeveloper** [metal-stack/metal-hammer#32]
Hi.

I am experiencing such an issue:

> metal-hammer/cmd$ go build -v -x
> WORK=/tmp/go-build852402972
> go: finding module for package github.com/metal-stack/metal-hammer/metal-core/client/machine
> \# get https://proxy.golang.org/github.com/@v/list
> go: finding module for package github.com/metal-stack/metal-hammer/metal-core/client/certs
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/client/@v/list
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/client/machine/@v/list
> \# get https://proxy.golang.org/github.com/metal-stack/@v/list
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/client/certs/@v/list
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/@v/list
> go: finding module for package github.com/metal-stack/metal-hammer/metal-core/models
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/models/@v/list
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/@v/list: 410 Gone (1.149s)
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/models/@v/list: 410 Gone (0.825s)
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/client/@v/list: 410 Gone (1.150s)
> \# get https://proxy.golang.org/github.com/@v/list: 410 Gone (1.152s)
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/client/machine/@v/list: 410 Gone (1.150s)
> \# get https://proxy.golang.org/github.com/metal-stack/metal-hammer/metal-core/client/certs/@v/list: 410 Gone (1.139s)
> \# get https://proxy.golang.org/github.com/metal-stack/@v/list: 410 Gone (1.150s)
> mkdir -p /home/oceanfish81/go/pkg/mod/cache/vcs # git3 https://github.com/metal-stack/metal-hammer
> \# lock /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1.lock# /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1 for git3 https://github.com/metal-stack/metal-hammer
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git ls-remote -q origin
> \# get https://github.com/?go-get=1
> \# get https://github.com/?go-get=1: 200 OK (0.180s)
> 1.436s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git ls-remote -q origin
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212 --
> 0.112s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212 --
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.075s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.127s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.122s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.083s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.077s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.064s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' b1688f4a3b7d --
> 0.132s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git -c log.showsignature=false log -n1 '--format=format:%H %ct %D' b1688f4a3b7d --
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.097s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.103s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.078s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> 0.067s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git for-each-ref --format %(refname) refs/tags --merged b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/client/machine/go.mod
> 0.043s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/client/machine/go.mod
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/client/go.mod
> 0.058s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/client/go.mod
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/client/certs/go.mod
> 0.044s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/client/certs/go.mod
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/models/go.mod
> 0.062s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/models/go.mod
> cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/go.mod
> 0.110s \# cd /home/oceanfish81/go/pkg/mod/cache/vcs/622413d38f6c59bcd46b0a1920eaf0b773f6f582a2351214bc1c1811b11886a1; git cat-file blob b1688f4a3b7dafcd77d1332fef0ec3f0a7b5e212:metal-core/go.mod
> root.go:15:2: no matching versions for query "latest"
> event/event.go:8:2: no matching versions for query "latest"
> event/event.go:9:2: no matching versions for query "latest"
> 

Something is wrong with the dependency management/metadata.

here is what & how I am using:

> $ go version && go env
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/metal-hammer/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build094063708=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
>

**Comment by majst01** [comment]
Thanks for the report, TBH i am not an expert in gollvm and why this can be useful. We are building metal-hammer and all other binaries with standard go 1.15.x :
```
go version go1.15.2 linux/amd64
```
And we do this most of the time inside a docker container and we call go build from a Makefile.

That said. the easiest way to compile metal-hammer is by simply running `make`

Hope that helps.

**Comment by Gerrit91** [comment]
If you still need help with this please re-open or visit our Slack channel https://slack.metal-stack.io/. Thank you. :)
