### ISSUE TITLE
remote logging

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-hammer#4]
with log15 we can do:

```go
h := log.MultiHandler(
		log.CallerFileHandler(log.StdoutHandler),
		log.Must.NetHandler("udp", "192.168.121.1:4713", log.JsonFormat()),
	)
```

and on the receiver side:

```bash
nc -lv 4713
```

But every log entry must then contain the machineID to be able to filter for a specific machine as the receiver (e.g. metal-core) will receive logs from all machines.

If we switch logger to zerolog for example, we can do remote logging via grpc:
https://github.com/rs/zerolog
https://github.com/cheapRoc/grpc-zerolog
Which is more convenient than udp sockets.

Or more general with netconsole from the metal-hammer-kernel:

https://wiki.archlinux.org/index.php/Netconsole

Is a weird interface but should be possible to log to the management server(s). Every metal-core can set a different management server on wish to the kernel cmdline.

The developer of golang netlink has a golang server for the netconsole standard: https://github.com/mdlayher/netconsole and the MAC-address is optional!

But still, we need to add the machineID somehow to the logs to have the context, otherwise it will all be random garbage. But pixiecore already knows from pxe magic the systemid which is the machineid in our case, @mwindower  did this magic to get the `pxe booting` event reported. Might be we can use that mechanism to configure console logging with this as prefix ??

No, prefixing is not possible from a kernel perspective. Must be done on the receiving side with a lookup on the macaddress.

I added netconsole support to the metal-hammer kernel to have at least a start.

/cc @mwennrich @Gerrit91

**Comment by Gerrit91** [comment]
Solved with #117.
