### ISSUE TITLE
Consider to create /var/lib/ on the nvme device instead the sata-dom

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-hammer#46]
In some situations where the worker node is in a very stressful situation, with lots of containers creating, the time to get configmaps/secrets mounted increases a lot. This slows down the start of all required containers.

If a nvme device is present use this to create the /var/lib filesystem on this device.

There are several options to do so:
- create a partition on the first nvme device and simple put a filesystem on it
- create a namespace on the first nvme device
- create a namespace on all existing nvme devices and create a raid1 above (this will left the size of both devices in the same size for usage by csi-driver-lvm)
- create 2 namespaces one on every disk, mount them as /var/lib and /var/log

**Comment by majst01** [comment]
we should address this with [MEP-8](https://github.com/metal-stack/docs/pull/54)

**Comment by Gerrit91** [comment]
References #22.

**Comment by majst01** [comment]
This is now possible since #50
