### ISSUE TITLE
Machines booting with inconsistent UUIDs

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-hammer#52]
We heavily rely on consistent / steady UUIDs of machines as the UUID is the primary key of the machine entity in the metal-api. 

For machines, the UUID is not generated in the metal-api but comes from the machine itself: It's emitted in the extended DHCP request of the PXE boot procedure (option 97 as described in [RFC4578](https://datatracker.ietf.org/doc/html/rfc4578#section-2.3)) and it can later also be read from `/sys/class/dmi/id/product_uuid`. This information from the DHCP extended broadcast allows us to track the machine lifecycle very early in the game (from the first time it tries to PXE boot).

The problem (at least with some of our Supermicro servers) is that the machine UUID that a machine reports consists of the MAC address from one of the network cards available for the PXE boot. When deactivating certain network cards through BIOS, the UUID may change.

When this happens, this results into an orphaned machine (liveliness dead) in the metal-api and a new machine with a fresh UUID that's directly sent into the crash loop because the metal-core prevents it from retrieving a boot image (see [this code fragment](https://github.com/metal-stack/metal-core/blob/v0.6.4/internal/endpoint/boot.go#L50)).

Different approaches for handling this issue might be:

- Configure the BIOS to only boot from a single network interface either trough manual configuration or automated in the metal-hammer (first approach causes high operational overhead, second approach probably introduces another big burden to integrate vendor support into go-hal)
- Generate the UUID for a machine in the metal-api and try not to rely on `/sys/class/dmi/id/product_uuid` (somehow tolerate machines without UUIDs but only with MAC addresses in the initial bootstrap phase --> give them their UUID in the register function)
- Somehow deal with multiple UUIDs for a single machine in the metal-api (there we know all the machine's mac addresses, but it's very unclear how this should be done without being extremely confusing)
- ...<your ideas?>

**Comment by majst01** [comment]
According to: https://smartdatacenter.topicbox.com/groups/sdc-discuss/T6163493dd08e0603-M3ade214b147fa7d3419e944d/server-uuids we are not the only facing this issue. But the system uuid can be set with sum according to: https://www.supermicro.com/support/faqs/faq.cfm?faq=33551

**Comment by Gerrit91** [comment]
> This means we should probably set the machine uuid to a new random one on the very first boot from the metal-hammer

I remember that we already saw some painful things happening when setting the UUID through sum. Then, sometimes Redfish reports a different UUID than the ipmitool and we did not find a way how to resolve this (persisted even after BMC reboot).

**Comment by Gerrit91** [comment]
In a discussion we decided that there is not much to do about because this behavior comes from the vendor and there is no good workaround to choose from.

Also we want to document this behavior in the metal-stack docs and write up a small paragraph about how to resolve this.
