### ISSUE TITLE
Report Power usage and consider deep sleep

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-hammer#6]
In order to save energy we should put the cpu's into deep sleep state as long as we stay in the long polling loop.

As we only have Intel CPU's with pstate enabled, all documentations relevant are here:

https://www.kernel.org/doc/html/v4.20/admin-guide/pm/intel_pstate.html

We can read power consumption on the machine with:

```bash
ipmitool dcmi power reading

    Instantaneous power reading:                    74 Watts
    Minimum during sampling period:                 50 Watts
    Maximum during sampling period:                195 Watts
    Average power reading over sample period:       56 Watts
    IPMI timestamp:                           Mon Jun 24 19:52:40 2019
    Sampling period:                          00278782 Seconds.
    Power reading state is:                   activated
```

which could probably be reported back to the api in a event to see the current power consumption.

**Comment by Gerrit91** [comment]
Implemented
