### ISSUE TITLE
Emit Planned Reboot Event when Rebooting after 3 days

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-hammer#92]
References https://github.com/metal-stack/metal-api/issues/324

**Comment by Gerrit91** [comment]
Looks from the code as if the metal-hammer already does this. But somehow I do not see it in the API. :disappointed: 

https://github.com/metal-stack/metal-hammer/blob/master/cmd/root.go#L71-L73

**Comment by majst01** [comment]
can this be closed ?

**Comment by Gerrit91** [comment]
I think so, yes.
